name: book
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - pip:
    - accessible-pygments
    - alabaster
    - anyio
    - argon2-cffi
    - argon2-cffi-bindings
    - arrow
    - async-lru
    - babel
    - bleach
    - cffi
    - charset-normalizer
    - contourpy
    - cycler
    - debugpy
    - defusedxml
    - docutils
    - fastjsonschema
    - fonttools
    - fqdn
    - imagesize
    - ipykernel
    - ipympl
    - ipython-genutils
    - isoduration
    - json5
    - jsonpointer
    - jsonschema
    - jsonschema-specifications
    - jupyter-book
    - jupyter-cache
    - jupyter-client
    - jupyter-contrib-core
    - jupyter-contrib-nbextensions
    - jupyter-core
    - jupyter-events
    - jupyter-highlight-selected-word
    - jupyter-lsp
    - jupyter-nbextensions-configurator
    - jupyter-server
    - jupyter-server-terminals
    - kiwisolver
    - latexcodec
    - linkify-it-py
    - lxml
    - markdown-it-py
    - markupsafe
    - matplotlib
    - mdit-py-plugins
    - mdurl
    - mistune
    - myst-nb
    - myst-parser
    - nbclient
    - nbconvert
    - nbformat
    - nest-asyncio
    - notebook
    - notebook-shim
    - numpy
    - overrides
    - pandas
    - pandocfilters
    - pillow
    - platformdirs
    - prometheus-client
    - psutil
    - pybtex
    - pybtex-docutils
    - pydata-sphinx-theme
    - pyparsing
    - pyzmq
    - referencing
    - rfc3339-validator
    - rfc3986-validator
    - rpds-py
    - scipy
    - send2trash
    - setuptools
    - sniffio
    - snowballstemmer
    - sphinx
    - sphinx-book-theme
    - sphinx-comments
    - sphinx-copybutton
    - sphinx-design
    - sphinx-external-toc
    - sphinx-gallery
    - sphinx-jupyterbook-latex
    - sphinx-multitoc-numbering
    - sphinx-thebe
    - sphinx-proof
    - sphinx-togglebutton
    - sphinxcontrib-applehelp
    - sphinxcontrib-bibtex
    - sphinxcontrib-devhelp
    - sphinxcontrib-htmlhelp
    - sphinxcontrib-jsmath
    - sphinxcontrib-qthelp
    - sphinxcontrib-serializinghtml
    - sqlalchemy
    - stack-data
    - tabulate
    - terminado
    - tinycss2
    - traitlets
    - types-python-dateutil
    - tzdata
    - uc-micro-py
    - uri-template
    - wcwidth
    - webcolors
    - webencodings
    - websocket-client
    - xarray
